AZURE_OPENAI_API_KEY = "<MY_API_KEY>"
AZURE_OPENAI_ENDPOINT = "https://<MY_URL>.openai.azure.com/openai/deployments/gpt-4/chat/completions?api-version=2025-01-01-preview"
AZURE_OPENAI_API_VERSION = "2025-01-01-preview"
EMBEDDING_DEPLOYMENT_NAME = "text-embedding-ada-002"
GPT_DEPLOYMENT_NAME = "<GPT_DEPLOYMENT_NAME>"
AZURE_SEARCH_ENDPOINT = "https://<SEARCH_URL>.search.windows.net"
AZURE_SEARCH_KEY = "<SEARCH_API_KEY>"
AZURE_SEARCH_INDEX_NAME = "rag-index"
